Repository fga-eps-mds/2019.2-Amika-Backend, pull requests merged in 2019-11, with the labels that each got.

#64 [HOT-FIX] Corrige escolha de tipo em Agenda
  amika/migrations/0004_auto_20191104_1258.py
  amika/models.py
Labels: bug, easy to solve

#62 [HOT-FIX] Remove urn não utilizada
  core/urls.py
Labels: bug, easy to solve

#67 [HOT-FIX] Corrige criação de Aluno pela interface do DRf
  amika/permissions.py
Labels: bug

#36 [HOT-FIX] Mostra cobertura de testes
  README.md
Labels: DevOps, EPS, bug

#69 [HOT-FIX] Mostra porcentagem da cobertura de testes
  .coveragerc
  amika/fixture.json
Labels: bug

#72 Adicionando método de autenticação do usuário na funcionalidade de humor
  amika/permissions.py
Labels: bug

#73 [HOT-FIX] Adiciona ordenações nas models
  amika/migrations/0006_auto_20191105_2213.py
  amika/models.py
Labels: bug

#68 Adiciona foto para aluno
  amika/migrations/0007_aluno_foto.py
  amika/models.py
  amika/serializers.py
  amika/tests/test_serializers.py
  amika/views.py
Labels: enhancement, feature

#75 [HOT-FIX] Permite exclusão de grupos com alunos
  amika/migrations/0008_auto_20191108_1627.py
  amika/models.py
Labels: bug

#82 [HOT-FIX] Corrige tipo de arquivo para perfil
  amika/migrations/0009_auto_20191114_1204.py
  amika/models.py
  requirements.txt
Labels: bug

#85 [HOT-FIX] Remove adição de foto na criação de aluno
  amika/serializers.py
Labels: bug

#87 [HOT-FIX] Corrige vizualização de media diretamente pela url
  core/urls.py
Labels: bug

#92 [HOT-FIX] Bagde de cobertura mostra percentual
  .travis.yml
  requirements.txt
Labels: bug

#94 [HOTFIX] Consertando erro de cadastrar aluno
  amika/views.py
Labels: bug

#95 Criando seeds dos humores
  seeds.json
Labels: MDS
