Repository fga-eps-mds/2019.2-Amika-Backend, pull requests merged in 2019-10, with the labels that each got.

#27 Criando arquivo de contribuição
  CONTRIBUTING.md
Labels: EPS, documentation, duplicate

#25 Adicionando licenca
  LICENSE
Labels: EPS, MDS, documentation, duplicate

#24 [DOC19] Criando README
  README.md
Labels: EPS, documentation, enhancement

#26 Criando código de conduta
  CODE_OF_CONDUCT.md
Labels: EPS, documentation, duplicate

#23 Us02 manter turma
  .travis.yml
  core/settings.py
  core/urls.py
  requirements.txt
  turmas/__init__.py
  turmas/admin.py
  turmas/apps.py
  turmas/migrations/0001_initial.py
  turmas/migrations/__init__.py
  turmas/models.py
  turmas/serializers.py
  turmas/tests/__init__.py
  turmas/tests/test_models.py
  turmas/tests/test_serializers.py
  turmas/tests/test_urls.py
  turmas/tests/test_views.py
  turmas/urls.py
  turmas/views.py
Labels: MDS, User Story, enhancement

#32 HOT-FIX Adiciona migração em deployments
  Procfile
Labels: DevOps, EPS, bug

#38 [US11] Manter agendas da felicidade
  alunos/serializers.py
  turmas/migrations/0002_agenda_atividade.py
  turmas/models.py
  turmas/serializers.py
  turmas/tests/test_models.py
  turmas/tests/test_serializers.py
  turmas/tests/test_urls.py
  turmas/tests/test_views.py
  turmas/urls.py
  turmas/views.py
Labels: EPS, MDS, User Story, enhancement

#34 Refatora Backend
  alunos/migrations/0001_initial.py
  alunos/migrations/0002_aluno_grupo.py
  alunos/migrations/__init__.py
  alunos/models.py
  alunos/serializers.py
  alunos/tests/__init__.py
  alunos/tests/test_models.py
  alunos/tests/test_serializers.py
  alunos/tests/test_urls.py
  alunos/tests/test_views.py
  alunos/urls.py
  alunos/views.py
  amika/__init__.py
  amika/admin.py
  amika/apps.py
  amika/fixture.json
  amika/migrations/0001_initial.py
  amika/migrations/__init__.py
  amika/models.py
  amika/serializers.py
  amika/tests/__init__.py
  amika/tests/test_models.py
  amika/tests/test_serializers.py
  amika/tests/test_urls.py
  amika/tests/test_views.py
  amika/urls.py
  amika/views.py
  core/settings.py
  core/urls.py
  grupos/admin.py
  grupos/apps.py
  grupos/migrations/0001_initial.py
  grupos/migrations/__init__.py
  grupos/models.py
  grupos/serializers.py
  grupos/tests/__init__.py
  grupos/tests/test_models.py
  grupos/tests/test_serializers.py
  grupos/tests/test_views.py
  grupos/urls.py
  grupos/views.py
  turmas/admin.py
  turmas/apps.py
  turmas/migrations/0001_initial.py
  turmas/migrations/0002_agenda_atividade.py
  turmas/migrations/__init__.py
  turmas/models.py
  turmas/serializers.py
  turmas/tests/__init__.py
  turmas/tests/test_models.py
  turmas/tests/test_serializers.py
  turmas/tests/test_urls.py
  turmas/tests/test_views.py
  turmas/urls.py
  turmas/views.py
Labels: bug

#48 Adiciona criterios de aceitacao
  .github/ISSUE_TEMPLATE/requisitar-funcionalidade.md
Labels: documentation, easy to solve, enhancement, good first issue, refactoring

#52 Issue 40 Adiciona seeds
  README.md
  seeds.json
Labels: enhancement, feature

#54 Criação do template para requisição de refatoração do backend
  .github/ISSUE_TEMPLATE/requisitar-refatoracao-do-backend.md
Labels: documentation, easy to solve, enhancement, good first issue
